# Information on the database
database:
  host: null
  dbname: null
  username: null
  password: null
  charset: 'utf8'

# Example
# database:
  # host: 'localhost:8889'
  # dbname: 'people'
  # username: 'root'
  # password: 'root'
  # charset: 'utf8'

# Show errors
withError: null # true || false || null
